# Build the Go Binary.
FROM golang:1.17 as build_strava
ENV CGO_ENABLED 0

# Copy the source code into the container.
COPY . /service

# Build the service binary.
WORKDIR /service
RUN go build

# Run the Go Binary in Alpine.
FROM alpine:3.15
COPY --from=build_strava /service/main /service/main
WORKDIR /service
CMD ["./main"]